### PR TITLE
feat(outline): outline enhancement

### PR DESCRIPTION
**Pull request by ringcrl**
feat(outline): outline enhancement

but...need help...

// TODO: fold all...

### CODE REVIEW

**Comment by neilsustc** [comment]
I have also investigated the vscode APIs but unfortunately "fold all" seems not possible now 😂. (We cannot change the collapse states programmatically)

But your initial problem should already be resolved since I made some changes to auto choose a proper collapse level (making the number of visible items less than 10)

**Comment by ringcrl** [comment]
Very embarrassed, see along while don't know how to modify it, but now feel very good, is conducive to the MD document reading. Thank you!
wx20180503-235149

**Comment by neilsustc** [comment]
Anyway, really appreciate for trying to help 😉

**Comment by neilsustc** [comment]
Close as VSCode has taken it over 😅

**Pull request closed without merging**
