### PR TITLE
Continue ordered lists longer than 9 items

### PR DESCRIPTION
**Pull request by rbolsius**
This pull request addresses a few issues with ordered lists.

1.  If an ordered list reaches the 9th item, then hitting `enter` or `ctrl+enter` does not continue the list.
2.  If an order list is formatted with more than one space between the marker and the text, and the list is continued, then the beginning of the text is not aligned with the previous line.  In other words, the new line does not keep the same number of spaces after the marker as the previous line.
3.  Hitting `ctrl+enter` on an empty marker sometimes inserts too many lines.

## Examples
In the examples below `|` represents the cursor position.

### Continuing the format of the previous list item

Test case:
```
1.  item one|
```
Press `enter`

Result before:
```
1.  item one
2. |
```

Result after:
```
1.  item one
2.  |
```

### Continuing a list with more than 9 or more items

Test case:
```
1.  item one
2.  item two
3.  item three
4.  item four
5.  item five
6.  item six
7.  item seven
8.  item eight
9.  item nine|
```
Press `enter`

Result before:
```
1.  item one
2.  item two
3.  item three
4.  item four
5.  item five
6.  item six
7.  item seven
8.  item eight
9.  item nine
|
```

Result after:
```
1.  item one
2.  item two
3.  item three
4.  item four
5.  item five
6.  item six
7.  item seven
8.  item eight
9.  item nine
10. |
```

### Pressing ctrl+enter on an empty list item

Test case:
```
1. item one
2. |
```
Press `ctrl+enter`

Result before:
```
1. item one


|
```

Result after:
```
1. item one

|
```

### CODE REVIEW

**Comment by neilsustc** [comment]
I'll have a look at it tomorrow. Thank you!

**Comment by neilsustc** [comment]
Looks great! Your codes are neater than mine.

One small question, I remember that [CommonMark Spec](http://spec.commonmark.org/) says that list has at most 9 items. (Of course we can support more list items if we want)
But I'm wondering how we deal with this situation, which is people might not know they will have more than 9 items in advance. If they just use 1 leading space and come to this

```
...
9. item nine|
```

What does it should be after pressing enter?

```
...
9. item nine
10. |
```

**Comment by rbolsius** [comment]
I was thinking about implementing a command at some point to renumber an ordered list.  I'm coming from Emacs to VS Code and the markdown extension in Emacs has a `markdown-cleanup-list-numbers` function that is very good.

If you run the command on a list list the following:

```
1. item one
2. item two
1. item three
2. item four
1. item five
2. item six
1. item seven
2. item eight
9. item nine
10. item ten|
```

It will both replace the markers with proper sequential numbers and in my customized version of the function, it will also pad with spaces so that all the item texts are aligned.

So, the result after running the command would be:

```
1.  item one
2.  item two
3.  item three
4.  item four
5.  item five
6.  item six
7.  item seven
8.  item eight
9.  item nine
10. item ten|
```

It is extremely useful when adding and removing list items.

I might submit separate pull request if I implement such a command in VS code.

Regarding the CommonMark spec, what it says is that the [order list marker][1] can be a sequence of one to nine digits (0-9).  So, that means "1.", "1)", "9.", "10.", "999999999." are all valid list markers.

> An ordered list marker is a sequence of 1-9 arabic digits (0-9), followed by either
>a . character or a ) character. (The reason for the length limit is that with 10 digits
>we start seeing integer overflows in some browsers.)

I frequently have lists with more than 9 items, which is supported by CommonMark.  On the other hand, what CommonMark supports (any integer up to nine digits long) is probably much longer than any ordered list would ever be in practice.  

[1]: http://spec.commonmark.org/0.27/#ordered-list-marker

**Comment by neilsustc** [comment]
Perfect! I really appreciate it.

**Comment by neilsustc** [comment]
Oops, I forgot to mention this PR in v0.8.0 release notes. 😮

Don't worry, I will announce this in the next version.

**Pull request merged**
