### PR TITLE
Add Unikey Handler

### PR DESCRIPTION
**Pull request by MagicPro1994**
Solve the typing problem with Unikey/GoTiengViet.

### CODE REVIEW

**Comment by neilsustc** [comment]
Let me have a look

**Comment by neilsustc** [comment]
Hi, I have reorganized the code according to my understanding. Could you update to the latest commit and help me check whether it still works well?

**Comment by MagicPro1994** [comment]
@neilsustc: It's okay when we type normal. It got some minor bugs when we type fast. But it's okay. It works as my function does.

**Comment by neilsustc** [comment]
Good to hear that. Will shipped with next release.

**Pull request merged**
