### PR TITLE
Auto renumbering improvements

### PR DESCRIPTION
**Pull request by rbolsius**
This pull request further improves the automatic renumbering of ordered
lists.

There are still some instances where renumbering does not occur
automatically.  Such cases include cutting and pasting text, deleting a
region of text, or typing a new list item in the middle of a list.  All these
additional cases could be more simply handled through a document change
listener, but renumbering the lists that frequently could also add a lot of
overhead.  So, if any edit leaves the list in a state that requires
renumbering simply move a line up and then down to trigger the remainder of
the list to be renumbered.

## Issues Fixed

1.  Renumbering list items now works when there are blank lines separating
    paragraphs of text within a single list item.

2.  Pressing `enter` at the end of an ordered list item already would insert
    a new list item and renumber the rest of the list.  However, if `enter`
    is pressed one more time, the empty list item is deleted, but in this
    case the rest of the list was not renumbered again to account for the
    deleted item.

3.  An ordered list should restart at 1 when it is preceded by regular text
    at the same indentation level as the list item or higher.

    First list:
    1.  item 1
    2.  item 2
    3.  item 3

    Second list (should restart at 1):

    1.  item 1
    2.  item 2
    3.  item 3
    4.  item 4

4.  Pressing `shift+tab` should automatically renumber the list just like `tab`
    does.

5.  Indenting or outdenting via `ctrl+]` or `ctrl+[` should automatically
    renumber the list.

6.  Selecting a range of lines and indenting via `tab` or `ctrl+]` or
    outdenting via `shift+tab` or `ctrl+[` should automatically renumber
    starting from the first line regardless whether the cursor is at the
    beginning or the end.

    1.  item 1
    2.  item 2
    3.  item 3
    4.  item 4

7.  Moving a selection of multiple lines up or down should automatically
    renumber.

8.  Copying a line up or down should automatically renumber.  It should work
    with the current line or a selection of multiple lines.

9.  Deleting a selection of multiple lines using `backspace` should
    automatically renumber.

10. Renumbering should try to preserve the previous indentation level of
    the text following the list item marker so that the text stays aligned

## Enhancements

1.  Press `shift+enter` to simply insert a new line without also inserting the
    next list item marker.  Useful when ending a nested list, but you want to
    continue writing at that indentation level.

    1.  item 1
    2.  item 2
    3.  item 3

## Demo

auto-renumbering

### CODE REVIEW

**Comment by rbolsius** [comment]
Working on fixing the test failures...

**Comment by neilsustc** [comment]
For the things that we can improve, I have this summary

1. List (range) detection
   - allow blank lines inside a list (point 1)
   - (point 3)
2. Fix trigger
   - after an empty list item deletion on `Enter` key (point 2)
   - after `Shift + Tab`, `Ctrl + [/]` (point 4, 5)
   - after copying line up/down (point 8)
3. Multi-line support (point 6, 7, 9)
4. Others
   - preserve list item indentation

Thanks for your effort and let's try to think of a good solution.

**Comment by rbolsius** [comment]
I agree.  These point fixes in this PR are just my own short-term attempt to solve most of the problems that I encounter with the auto renumbering so that it can be used with longer lists containing wrapped text.

I think the best solution longer term for real-time renumbering is to listen for document change events, filtering out the ones that could not affect list numbering for performance reasons.  Then for the remaining change events, the extension could find all the line ranges of all the lists affected by the edits and renumber them starting from the beginning of the list in one single pass.

The key will be to make the list line range identification and subsequent renumbering as fast as possible.

To make the renumbering efficient, the renumbering function could renumber all levels of the list in a single pass to ensure that the algorithm remains O(n).  As it iterates over the lines, the function could maintain a stack of the all the current list item numbers at each nested level.  This way all the nested lists can be renumbered in the same pass as the top level list since edits can often overlap multiple levels of list items.

**Comment by neilsustc** [comment]
> As it iterates over the lines, the function could maintain a stack of the all the current list item numbers at each nested level.

This is exactly what a parser does 🤣. I also realized it in the very beginning of implementing this feature. And then, I chose the current approach (which is much simpler/faster in most cases).

**Comment by rbolsius** [comment]
I think the single pass approach may be even better performing than the current implementation since it will not have to scan backwards for each marker to find the previous number.  Also, it doesn't really have to be a full parser, just limited to list items.  So, it should not be very complex.

**Comment by rbolsius** [comment]
Hi, I've fixed the problems in my original PR that were causing the test failures in the existing list editing tests, and I've added new tests for the new features.

I think this is an incremental improvement over the current features, and it solves the problems I've listed above, but it is not the more general solution that we discussed.  I just wanted to get this PR closed so that the worst issues I'm facing are fixed, while we can keep working on a more elegant, general solution.  I have a start, but it will take more time.

Also, I don't know why but the test "Enter key. Respect indentation rules" started failing in AppVeyor, although it was passing in AppVeyor earlier, and it still passes when I run the tests locally.  I don't think that I have changed anything that would affect the indentation in that area as far as I can see.  When I debug, I see that it still recognizes that the cursor is inside a fenced block and calls asNormal('enter', modifiers).  So, I don't understand why the line is not indented when run from AppVeyor.

**Comment by rbolsius** [comment]
It appears that the same "Respect indentation rules" test failed also in commit dc3536c9ef762180e2407eaeece1e5e9cc4b8faf, but I can't see the reason for it to fail in that commit either.  So, I will assume that the failure is unrelated to the changes in this PR.

**Comment by neilsustc** [comment]
Nice work! 🍻

**Comment by ZhiboWong** [comment]
``Renumbering list items now works when there are blank lines separating paragraphs of text within a single list item.``
Why I insert a blank lines between two paragraphs, they are not numbered . Do I have any misunderstanding about auto number list? What should I do for auto numbering ?

**Comment by yzhang-gh** [comment]
It would be better if you can open a new issue and tell us a minimal example, what you did, and what you expected.

**Pull request merged**
